const CATEGORIES = [
  { id: 'love',          label: 'Love',         icon: '💕' },
  { id: 'spicy',         label: 'Spicy',        icon: '🌶️' },
  { id: 'ethics',        label: 'Ethics',       icon: '⚖️' },
  { id: 'personality',   label: 'Personality',  icon: '🧠' },
  { id: 'life',          label: 'Life & Death', icon: '☠️' },
  { id: 'wild',          label: 'Wild Card',    icon: '🃏' },
  { id: 'nostalgia',     label: 'Nostalgia',    icon: '📼' },
  { id: 'opinions',      label: 'Hot Takes',    icon: '🔥' },
  { id: 'hypotheticals', label: 'Would You?',   icon: '🤔' },
];

const QUESTIONS = {
  love: [
    { q: "What's most important to you in a relationship?",          opts: ["Physical attraction", "Emotional connection", "Shared interests", "Loyalty"] },
    { q: "What's your love language?",                               opts: ["Words of affirmation", "Acts of service", "Physical touch", "Quality time"] },
    { q: "How would you want someone to propose to you?",            opts: ["Private & intimate", "Big public gesture", "Totally spontaneous", "I'd rather propose"] },
    { q: "What's your ideal first date?",                            opts: ["Dinner out", "Netflix at home", "Outdoor adventure", "Bar hopping"] },
    { q: "Have you ever been the one to break someone's heart?",     opts: ["Yes, more than once", "Yes, once", "No, never", "I plead the fifth"] },
    { q: "How many people have you genuinely been in love with?",    opts: ["Zero", "One", "Two or three", "Four or more"] },
    { q: "Your biggest relationship deal-breaker is?",               opts: ["Bad hygiene", "Lying", "Jealousy", "Financial irresponsibility"] },
    { q: "How long would you wait before becoming official with someone?", opts: ["A few weeks", "1-3 months", "6 months+", "I go with the flow"] },
    { q: "What do you do when you have feelings for someone?",       opts: ["Tell them directly", "Drop hints and wait", "Do nothing and hope", "Ask a mutual friend"] },
    { q: "How quickly do you usually fall for someone?",             opts: ["Instantly — I catch feelings fast", "Slowly over months", "Only after deep connection", "I don't really 'fall'"] },
    { q: "What's your honest approach to an argument with a partner?", opts: ["Win at all costs", "Listen and compromise", "Shut down and go quiet", "Apologise first, think later"] },
    { q: "How do you feel about long-distance relationships?",       opts: ["Could make it work", "Tried it — never again", "Wouldn't even start one", "Depends on the person"] },
  ],
  spicy: [
    { q: "Where's the wildest place you've ever made out?",          opts: ["In a car", "At a party/bar", "In public outdoors", "Somewhere I won't say"] },
    { q: "How many people have you kissed in total?",                opts: ["1-3", "4-10", "11-20", "I stopped counting"] },
    { q: "Would you ever date someone your friend had a crush on?",  opts: ["Yes, if they said it's okay", "Never, that's a rule", "Depends on the friend", "Depends on the crush"] },
    { q: "Would you go on a date with a stranger from an app?",      opts: ["Already have", "Yes, I'm open to it", "Maybe, but nervous", "No way"] },
    { q: "How soon is too soon to say 'I love you'?",                opts: ["Under 1 month", "1-3 months", "6 months+", "It depends"] },
    { q: "What's your 'type' physically?",                           opts: ["Tall & muscular", "Short & cute", "Doesn't matter", "It's complicated"] },
    { q: "Most embarrassing thing that happened on a date?",         opts: ["Awkward silence for 5+ min", "Said the wrong name", "Phone died mid-date", "Much worse..."] },
    { q: "Have you ever had a crush on someone in this room?",       opts: ["Yes, right now", "Yes, in the past", "No, never", "I'll never tell"] },
    { q: "Have you ever sent a risky text to the wrong person?",     opts: ["Yes, and it was bad", "Yes, but they were cool about it", "Almost but I caught it", "Never, I'm careful"] },
    { q: "What's the most you've done to impress someone you liked?", opts: ["Changed how I dress/act", "Learned a skill for them", "Lied about myself", "Stalked their interests online"] },
    { q: "Have you ever been on more than one date in a single day?", opts: ["Yes, more than once", "Yes, once", "No but I would", "Never — that's chaotic"] },
    { q: "Biggest thing you've lied about on a first date?",         opts: ["My job or ambitions", "How over my ex I am", "My opinions to match theirs", "I don't lie on dates"] },
  ],
  ethics: [
    { q: "If you found $500 cash on the street, what would you do?", opts: ["Keep it all", "Try to find the owner", "Donate some, keep some", "Turn it in to police"] },
    { q: "A friend's partner is cheating on them. You find out. What do you do?", opts: ["Tell the friend immediately", "Confront the cheater first", "Stay out of it", "It depends on the situation"] },
    { q: "Would you lie to avoid going to an event you don't want to attend?", opts: ["Yes, I do it regularly", "Yes, but I feel guilty", "No, I'm honest", "I just go anyway"] },
    { q: "A cashier gives you $20 too much in change. What do you do?", opts: ["Give it back", "Keep it quietly", "Depends how rich the store looks", "It's happened and I kept it"] },
    { q: "Would you ghost someone to avoid an awkward conversation?", opts: ["I've done it before", "I'd want to but wouldn't", "No, I'd have the talk", "Ghosting is never okay"] },
    { q: "How honest are you in your online profiles?",              opts: ["100% honest", "Mostly honest", "Selective truth", "Curated fantasy"] },
    { q: "Would you snoop through a partner's phone if you had the chance?", opts: ["Yes, without hesitation", "Only if I was suspicious", "I'd want to but wouldn't", "Never — total violation"] },
    { q: "If you could read minds for one day, would you?",          opts: ["Absolutely yes", "Yes but I'd regret it", "Depends on whose", "No, ignorance is bliss"] },
    { q: "Your friend asks your opinion on their terrible new partner. You say...", opts: ["I'm honest — they deserve to know", "I hint but don't say it outright", "I say nothing and wait", "I make up something nice"] },
    { q: "You see a colleague taking credit for your work. You...",   opts: ["Call it out publicly", "Pull them aside privately", "Tell your manager", "Let it go to avoid drama"] },
    { q: "How often do you tip when you genuinely had bad service?",  opts: ["Always — it's not their fault", "Usually, but less", "Only if it was decent", "No tip for bad service"] },
    { q: "You accidentally break something at a friend's place. You...", opts: ["Tell them immediately", "Quietly fix or replace it", "Hope they don't notice", "Blame it on someone else"] },
  ],
  personality: [
    { q: "How do you handle conflict?",                              opts: ["Confront it head-on", "Avoid until it blows over", "Talk it through calmly", "Passive-aggressively"] },
    { q: "Your biggest flaw is...",                                  opts: ["I overthink everything", "I'm too stubborn", "I can be selfish", "I procrastinate badly"] },
    { q: "How do you recharge after a draining week?",               opts: ["Solo time at home", "Going out with friends", "Exercise or outdoors", "Sleep and Netflix"] },
    { q: "Which best describes you at a party?",                     opts: ["Center of attention", "Mingling in small groups", "Sticking with my friends", "Counting down to leave"] },
    { q: "What's your coping mechanism for stress?",                 opts: ["Exercise", "Eat junk food", "Talk to someone", "Bottle it up"] },
    { q: "How organized are you really?",                            opts: ["Extremely organized", "Pretty tidy", "Organized chaos", "Total disaster"] },
    { q: "Your friends would describe you as...",                    opts: ["The funny one", "The responsible one", "The wild one", "The mysterious one"] },
    { q: "When a friend cancels plans, you feel...",                 opts: ["Relieved, honestly", "A little annoyed", "Fine, things happen", "Hurt — I was looking forward to it"] },
    { q: "How do you usually make big decisions?",                   opts: ["Gut feeling immediately", "Long pros/cons list", "Ask everyone I trust", "Delay until forced to choose"] },
    { q: "What motivates you most?",                                 opts: ["Recognition from others", "Personal pride", "Money / security", "Making people around me happy"] },
    { q: "How do you act when you're jealous?",                      opts: ["I admit it openly", "I go cold and distant", "I overcompensate with confidence", "I pretend I don't care"] },
    { q: "Your honest relationship with your phone is...",           opts: ["I check it constantly", "I use it a lot but manage it", "I could go without it for days", "It genuinely controls me"] },
  ],
  life: [
    { q: "If you had one year left to live, what would you do?",     opts: ["Travel the world", "Spend time with family", "Chase one big dream", "Party hard and enjoy it"] },
    { q: "What's the biggest risk you've ever taken?",               opts: ["Career change", "Moving cities/countries", "A relationship leap", "Something financial"] },
    { q: "What do you think happens after we die?",                  opts: ["Heaven/Hell", "Reincarnation", "Nothing — lights out", "I genuinely don't know"] },
    { q: "What's your biggest regret so far?",                       opts: ["A missed opportunity", "A broken relationship", "Not starting sooner on a goal", "Something I'd never say out loud"] },
    { q: "If you could live in any decade, which would you pick?",   opts: ["The 70s", "The 80s", "The 90s", "I like right now"] },
    { q: "What would you want your legacy to be?",                   opts: ["A loving parent/partner", "A successful career", "An adventure-filled life", "Making people laugh"] },
    { q: "One thing you'd change about how you were raised?",        opts: ["More freedom", "More discipline", "More emotional support", "I wouldn't change anything"] },
    { q: "How do you feel about death?",                             opts: ["I think about it a lot", "I try not to think about it", "I've made peace with it", "It genuinely scares me"] },
    { q: "At what age do you think you were happiest?",              opts: ["Childhood — no responsibilities", "Teens — felt invincible", "20s — freedom and energy", "Right now, actually"] },
    { q: "What is success to you?",                                  opts: ["Financial freedom", "Doing work I love", "Strong relationships", "Feeling healthy and at peace"] },
    { q: "How do you feel about where you are in life right now?",   opts: ["Exactly where I want to be", "A bit behind where I hoped", "Off-track but getting there", "Completely lost — and that's okay"] },
    { q: "If you could give your younger self one piece of advice?", opts: ["Worry less about what people think", "Take more risks earlier", "Save your money", "Don't date that person"] },
  ],
  wild: [
    { q: "What's the most illegal thing you've ever done?",          opts: ["Jaywalked / minor traffic", "Something involving substances", "Something I can't say here", "I'm basically a saint"] },
    { q: "Your most embarrassing drunk story involves...",           opts: ["Saying something I regret", "A physical incident", "A total stranger", "I was sober! I swear."] },
    { q: "Have you ever stalked an ex's social media recently?",     opts: ["Yes, this week", "Yes, occasionally", "Only once after the breakup", "Never — I'm evolved"] },
    { q: "If your texts were projected here right now, how nervous are you?", opts: ["0/10 — nothing to hide", "3/10 — mildly concerned", "7/10 — pretty nervous", "10/10 — please don't"] },
    { q: "What's a secret you've never told anyone in this room?",   opts: ["Something about work", "Something romantic", "Something embarrassing", "Not telling — DRINK."] },
    { q: "Would you rather lose all your money or all your memories?", opts: ["Lose money", "Lose memories", "Neither — this is cruel", "Depends on the memories"] },
    { q: "What's the most scandalous text you've ever sent?",        opts: ["A spicy late-night text", "A passive-aggressive message", "A wrong-person accident", "I delete everything"] },
    { q: "On a scale of 1-4, how good are you in bed?",              opts: ["1 — still learning", "2 — getting there", "3 — pretty solid", "4 — legendary"] },
    { q: "Have you ever pretended to be someone you're not online?", opts: ["Yes, with a fake profile", "Yes, just exaggerated a bit", "No, but I've been tempted", "Absolutely not"] },
    { q: "Worst lie you've told to get out of plans?",               opts: ["Fake illness", "Family emergency", "Work emergency", "I just ghost — no excuse given"] },
    { q: "What's the most embarrassing thing on your phone right now?", opts: ["A cringey photo album", "A group chat I should leave", "Browsing history I can't explain", "My notes app — do NOT open"] },
    { q: "Have you ever done something purely to make someone jealous?", opts: ["Yes and it worked", "Yes but it backfired", "I wanted to but didn't", "Never — I'm above that"] },
  ],
  nostalgia: [
    { q: "What childhood fear do you lowkey still have?",            opts: ["The dark", "Something under the bed", "Heights", "Being home alone"] },
    { q: "What best describes your teenage self?",                   opts: ["The class clown", "The quiet one", "Tried too hard to be cool", "Genuinely didn't care"] },
    { q: "What show or movie defined your childhood?",               opts: ["A cartoon series", "A Disney/Pixar film", "A teen drama", "Something my parents shouldn't have let me watch"] },
    { q: "What's your most cringe teenage memory?",                  opts: ["Something I said to a crush", "A fashion choice I made", "A social media post", "A phase I went through"] },
    { q: "What did you want to be when you grew up?",                opts: ["Something creative (artist, actor)", "Something heroic (doctor, firefighter)", "Something cool (athlete, pop star)", "I genuinely had no idea"] },
    { q: "Your first heartbreak was caused by...",                   opts: ["A romantic rejection", "Losing a friendship", "Moving away or someone leaving", "Something family-related"] },
    { q: "What were you like at school?",                            opts: ["Popular and sociable", "Nerdy and studious", "Sporty and competitive", "On the fringes — doing my own thing"] },
    { q: "What's something from your childhood you genuinely miss?", opts: ["Having zero responsibilities", "A specific toy or game", "Saturday morning cartoons", "Not having a phone"] },
    { q: "How would your childhood best friend describe you back then?", opts: ["Loud and always laughing", "Bossy but loyal", "The shy one who warmed up", "The one with the wildest ideas"] },
    { q: "What's the most trouble you ever got into as a kid?",      opts: ["Sneaking out", "Breaking something expensive", "Lying to parents about where I was", "A fight or falling out with someone"] },
  ],
  opinions: [
    { q: "What's your most controversial food opinion?",             opts: ["Pineapple belongs on pizza", "Cilantro tastes like soap and ruins food", "Ketchup doesn't belong on eggs", "Breakfast food is overrated"] },
    { q: "Which overrated thing do you genuinely not get the hype about?", opts: ["A hugely popular TV show", "A beloved food or drink", "A famous travel destination", "A cultural phenomenon everyone loves"] },
    { q: "What's your hottest take on social media?",                opts: ["Instagram ruins relationships", "Twitter/X is pure toxicity", "TikTok is genuinely rotting brains", "LinkedIn is the most fake platform"] },
    { q: "What's an unpopular opinion you'd die on a hill for?",     opts: ["Something about pop culture", "Something about dating/relationships", "Something about society/politics", "Something about food or lifestyle"] },
    { q: "Which life milestone is the most overrated?",              opts: ["Buying a house", "Getting married", "Having kids", "Going to university"] },
    { q: "Most overrated quality people claim to want in a partner?", opts: ["Tall", "Funny", "Ambitious", "Kind"] },
    { q: "What do you secretly judge people for?",                   opts: ["Bad taste in music or TV", "Being rude to service staff", "Excessive social media posting", "Being chronically late"] },
    { q: "What's wrong with how most people spend their money?",     opts: ["Too much on going out", "Overpriced coffee addiction", "Buying things to impress others", "Subscriptions they never use"] },
    { q: "What do you think is the most toxic thing normalised in dating culture?", opts: ["Playing hard to get", "Keeping situationships going", "Ghosting", "Treating dates like job interviews"] },
    { q: "Which popular personality type label is the most overused?", opts: ["'I'm an introvert'", "'I'm an empath'", "'I'm a Virgo, that's why'", "'I have attachment issues'"] },
  ],
  hypotheticals: [
    { q: "Would you rather know the exact date of your death or the exact cause?", opts: ["The date — I'd plan everything", "The cause — I'd avoid it", "Neither — ignorance is bliss", "Both, I want the full picture"] },
    { q: "If you had to switch careers tomorrow, what would you do?", opts: ["Something creative", "Something outdoors or physical", "Something that helps people", "I'd start a business"] },
    { q: "Would you rather be famous but broke, or rich but completely unknown?", opts: ["Famous and broke — the attention is worth it", "Rich and unknown — peace and freedom", "Depends on the kind of fame", "I couldn't handle either extreme"] },
    { q: "If you could only eat one meal for the rest of your life, what would it be?", opts: ["A classic roast", "A big breakfast", "Pizza or pasta", "Something from another culture"] },
    { q: "Would you rather have a rewind button or a pause button for your life?", opts: ["Rewind — I'd fix so much", "Pause — I need more time", "Rewind for one specific moment", "Pause during the best moments"] },
    { q: "If your life were a movie genre, what would it be?",        opts: ["Romantic comedy", "Thriller with twists", "Coming-of-age drama", "Low-budget indie nobody watched"] },
    { q: "Would you rather give up alcohol or social media for a year?", opts: ["Give up alcohol — easy", "Give up social media — easy", "Alcohol... but it'd be hard", "Social media... but it'd be hard"] },
    { q: "If you could live anywhere in the world, where would you go?", opts: ["Somewhere warm and coastal", "A buzzing international city", "Peaceful countryside", "Wherever I am now, honestly"] },
    { q: "Would you rather always know when someone is lying to you, or be able to lie without anyone ever knowing?", opts: ["Know when others lie — trust is everything", "Lie freely — the power is appealing", "Know when others lie — I'd use it carefully", "Lie freely — just white lies, I promise"] },
    { q: "If you could be world-class at one thing overnight, what would you pick?", opts: ["A sport or physical skill", "A creative skill (music, art, writing)", "A social skill (public speaking, charisma)", "Something that makes money"] },
  ],
};
