const CATEGORIES = [
  { id: 'love',          label: 'Love',         icon: '💕' },
  { id: 'spicy',         label: 'Spicy',        icon: '🌶️' },
  { id: 'ethics',        label: 'Ethics',       icon: '⚖️' },
  { id: 'personality',   label: 'Personality',  icon: '🧠' },
  { id: 'life',          label: 'Life & Death', icon: '☠️' },
  { id: 'wild',          label: 'Wild Card',    icon: '🃏' },
  { id: 'nostalgia',     label: 'Nostalgia',    icon: '📼' },
  { id: 'opinions',      label: 'Hot Takes',    icon: '🔥' },
  { id: 'hypotheticals', label: 'Would You?',   icon: '🤔' },
  { id: 'money',         label: 'Money',        icon: '💸' },
  { id: 'travel',        label: 'Travel',       icon: '✈️' },
  { id: 'work',          label: 'Work Life',    icon: '💼' },
  { id: 'deepdark',      label: 'Deep Dark',    icon: '🕳️' },
];

const QUESTIONS = {
  love: [
    { q: "What's most important to you in a relationship?",          opts: ["Physical attraction", "Emotional connection", "Shared interests", "Loyalty"] },
    { q: "What's your love language?",                               opts: ["Words of affirmation", "Acts of service", "Physical touch", "Quality time"] },
    { q: "How would you want someone to propose to you?",            opts: ["Private & intimate", "Big public gesture", "Totally spontaneous", "I'd rather propose"] },
    { q: "What's your ideal first date?",                            opts: ["Dinner out", "Netflix at home", "Outdoor adventure", "Bar hopping"] },
    { q: "Have you ever been the one to break someone's heart?",     opts: ["Yes, more than once", "Yes, once", "No, never", "I plead the fifth"] },
    { q: "How many people have you genuinely been in love with?",    opts: ["Zero", "One", "Two or three", "Four or more"] },
    { q: "Your biggest relationship deal-breaker is?",               opts: ["Bad hygiene", "Lying", "Jealousy", "Financial irresponsibility"] },
    { q: "How long would you wait before becoming official with someone?", opts: ["A few weeks", "1-3 months", "6 months+", "I go with the flow"] },
    { q: "What do you do when you have feelings for someone?",       opts: ["Tell them directly", "Drop hints and wait", "Do nothing and hope", "Ask a mutual friend"] },
    { q: "How quickly do you usually fall for someone?",             opts: ["Instantly — I catch feelings fast", "Slowly over months", "Only after deep connection", "I don't really 'fall'"] },
    { q: "What's your honest approach to an argument with a partner?", opts: ["Win at all costs", "Listen and compromise", "Shut down and go quiet", "Apologise first, think later"] },
    { q: "How do you feel about long-distance relationships?",       opts: ["Could make it work", "Tried it — never again", "Wouldn't even start one", "Depends on the person"] },
    { q: "Would you get back together with an ex?",                  opts: ["Yes, if they'd changed", "Never — once is enough", "Depends on which ex", "I've already done it"] },
    { q: "How much alone time do you need in a relationship?",       opts: ["A lot — I need space", "Some — balance is key", "Very little — I like closeness", "I haven't figured this out yet"] },
    { q: "What's your red flag that others somehow miss?",           opts: ["I go very cold when upset", "I need constant reassurance", "I get too intense too fast", "I compare people to my exes"] },
    { q: "Do you believe in soulmates?",                             opts: ["Yes, completely", "Romantically no — but platonically, yes", "No, love is a choice", "I want to but I'm not sure"] },
    { q: "What ends a relationship faster for you?",                 opts: ["Feeling disrespected", "Growing apart silently", "A single big betrayal", "Losing the spark gradually"] },
    { q: "How do you know you're truly over someone?",               opts: ["When I stop checking their socials", "When I can talk about them without feeling anything", "When I meet someone new", "I'm not sure I ever fully get over people"] },
  ],
  spicy: [
    { q: "Where's the wildest place you've ever made out?",          opts: ["In a car", "At a party/bar", "In public outdoors", "Somewhere I won't say"] },
    { q: "How many people have you kissed in total?",                opts: ["1-3", "4-10", "11-20", "I stopped counting"] },
    { q: "Would you ever date someone your friend had a crush on?",  opts: ["Yes, if they said it's okay", "Never, that's a rule", "Depends on the friend", "Depends on the crush"] },
    { q: "Would you go on a date with a stranger from an app?",      opts: ["Already have", "Yes, I'm open to it", "Maybe, but nervous", "No way"] },
    { q: "How soon is too soon to say 'I love you'?",                opts: ["Under 1 month", "1-3 months", "6 months+", "It depends"] },
    { q: "What's your 'type' physically?",                           opts: ["Tall & muscular", "Short & cute", "Doesn't matter", "It's complicated"] },
    { q: "Most embarrassing thing that happened on a date?",         opts: ["Awkward silence for 5+ min", "Said the wrong name", "Phone died mid-date", "Much worse..."] },
    { q: "Have you ever had a crush on someone in this room?",       opts: ["Yes, right now", "Yes, in the past", "No, never", "I'll never tell"] },
    { q: "Have you ever sent a risky text to the wrong person?",     opts: ["Yes, and it was bad", "Yes, but they were cool about it", "Almost but I caught it", "Never, I'm careful"] },
    { q: "What's the most you've done to impress someone you liked?", opts: ["Changed how I dress/act", "Learned a skill for them", "Lied about myself", "Stalked their interests online"] },
    { q: "Have you ever been on more than one date in a single day?", opts: ["Yes, more than once", "Yes, once", "No but I would", "Never — that's chaotic"] },
    { q: "Biggest thing you've lied about on a first date?",         opts: ["My job or ambitions", "How over my ex I am", "My opinions to match theirs", "I don't lie on dates"] },
    { q: "How many situationships have you been in?",                opts: ["Zero — I don't do that", "One, accidentally", "Two or three", "More than I can count"] },
    { q: "Have you ever fancied your friend's partner?",             opts: ["Yes and I told no one", "Yes and I removed myself from the situation", "No, never", "I plead the fifth"] },
    { q: "What's the boldest move you've made on someone?",          opts: ["Slid into their DMs cold", "Kissed them first", "Confessed feelings out of nowhere", "Nothing — I'm a coward romantically"] },
    { q: "How would you rate your flirting skills honestly?",        opts: ["Terrible — oblivious to everything", "Average — I try but fumble", "Pretty good when I'm confident", "Elite — I could teach a class"] },
    { q: "Have you ever dated two people at the same time without them knowing?", opts: ["Yes, and I'd do it again", "Yes, and I regret it", "No, but I've been tempted", "Never — that's not okay"] },
    { q: "What's the most romantic thing someone has ever done for you?", opts: ["A grand gesture", "Something quietly thoughtful", "Said exactly the right thing", "I'm still waiting for that"] },
  ],
  ethics: [
    { q: "If you found $500 cash on the street, what would you do?", opts: ["Keep it all", "Try to find the owner", "Donate some, keep some", "Turn it in to police"] },
    { q: "A friend's partner is cheating on them. You find out. What do you do?", opts: ["Tell the friend immediately", "Confront the cheater first", "Stay out of it", "It depends on the situation"] },
    { q: "Would you lie to avoid going to an event you don't want to attend?", opts: ["Yes, I do it regularly", "Yes, but I feel guilty", "No, I'm honest", "I just go anyway"] },
    { q: "A cashier gives you $20 too much in change. What do you do?", opts: ["Give it back", "Keep it quietly", "Depends how rich the store looks", "It's happened and I kept it"] },
    { q: "Would you ghost someone to avoid an awkward conversation?", opts: ["I've done it before", "I'd want to but wouldn't", "No, I'd have the talk", "Ghosting is never okay"] },
    { q: "How honest are you in your online profiles?",              opts: ["100% honest", "Mostly honest", "Selective truth", "Curated fantasy"] },
    { q: "Would you snoop through a partner's phone if you had the chance?", opts: ["Yes, without hesitation", "Only if I was suspicious", "I'd want to but wouldn't", "Never — total violation"] },
    { q: "If you could read minds for one day, would you?",          opts: ["Absolutely yes", "Yes but I'd regret it", "Depends on whose", "No, ignorance is bliss"] },
    { q: "Your friend asks your opinion on their terrible new partner. You say...", opts: ["I'm honest — they deserve to know", "I hint but don't say it outright", "I say nothing and wait", "I make up something nice"] },
    { q: "You see a colleague taking credit for your work. You...",   opts: ["Call it out publicly", "Pull them aside privately", "Tell your manager", "Let it go to avoid drama"] },
    { q: "How often do you tip when you genuinely had bad service?",  opts: ["Always — it's not their fault", "Usually, but less", "Only if it was decent", "No tip for bad service"] },
    { q: "You accidentally break something at a friend's place. You...", opts: ["Tell them immediately", "Quietly fix or replace it", "Hope they don't notice", "Blame it on someone else"] },
    { q: "Would you use a friend's streaming login without telling them?", opts: ["Already doing it", "I'd ask first", "No — I'd just pay for my own", "I'd feel too guilty"] },
    { q: "If you knew you wouldn't get caught, would you speed on an empty road?", opts: ["Absolutely", "Probably a little", "No — rules exist for a reason", "I already do this"] },
    { q: "You find out a close friend lied to you about something small. You...", opts: ["Bring it up — even small lies matter", "Let it go, it was harmless", "File it away and watch more carefully", "Feel hurt but say nothing"] },
    { q: "Would you pretend to be sick to get out of jury duty?",     opts: ["Yes, in a heartbeat", "I'd find a legal way out", "No — it's a civic duty", "I'd actually want to do it"] },
  ],
  personality: [
    { q: "How do you handle conflict?",                              opts: ["Confront it head-on", "Avoid until it blows over", "Talk it through calmly", "Passive-aggressively"] },
    { q: "Your biggest flaw is...",                                  opts: ["I overthink everything", "I'm too stubborn", "I can be selfish", "I procrastinate badly"] },
    { q: "How do you recharge after a draining week?",               opts: ["Solo time at home", "Going out with friends", "Exercise or outdoors", "Sleep and Netflix"] },
    { q: "Which best describes you at a party?",                     opts: ["Center of attention", "Mingling in small groups", "Sticking with my friends", "Counting down to leave"] },
    { q: "What's your coping mechanism for stress?",                 opts: ["Exercise", "Eat junk food", "Talk to someone", "Bottle it up"] },
    { q: "How organized are you really?",                            opts: ["Extremely organized", "Pretty tidy", "Organized chaos", "Total disaster"] },
    { q: "Your friends would describe you as...",                    opts: ["The funny one", "The responsible one", "The wild one", "The mysterious one"] },
    { q: "When a friend cancels plans, you feel...",                 opts: ["Relieved, honestly", "A little annoyed", "Fine, things happen", "Hurt — I was looking forward to it"] },
    { q: "How do you usually make big decisions?",                   opts: ["Gut feeling immediately", "Long pros/cons list", "Ask everyone I trust", "Delay until forced to choose"] },
    { q: "What motivates you most?",                                 opts: ["Recognition from others", "Personal pride", "Money / security", "Making people around me happy"] },
    { q: "How do you act when you're jealous?",                      opts: ["I admit it openly", "I go cold and distant", "I overcompensate with confidence", "I pretend I don't care"] },
    { q: "Your honest relationship with your phone is...",           opts: ["I check it constantly", "I use it a lot but manage it", "I could go without it for days", "It genuinely controls me"] },
    { q: "How do you behave in a group project?",                    opts: ["Take charge whether asked or not", "Do my fair share, no more", "Let others lead and fill gaps", "Stress about everyone else's work"] },
    { q: "What does your inner critic usually say to you?",          opts: ["You're not good enough", "You're too much for people", "You're behind where you should be", "You care too much what others think"] },
    { q: "How do you respond when someone wrongs you?",              opts: ["Forgive quickly and move on", "Forgive but never forget", "Need a proper apology first", "Hold grudges longer than I should"] },
    { q: "What's your relationship with praise?",                    opts: ["I love it — I need it", "I appreciate it but feel awkward", "I'm suspicious of it", "I deflect every compliment"] },
    { q: "When you're upset, what do you actually do?",              opts: ["Talk to someone immediately", "Write it out or journal", "Distract myself until it fades", "Sit in it alone until I'm okay"] },
    { q: "Which bad habit are you most guilty of?",                  opts: ["Doom scrolling at 2am", "Leaving things to the last minute", "Saying yes when I mean no", "Comparing myself to others constantly"] },
  ],
  life: [
    { q: "If you had one year left to live, what would you do?",     opts: ["Travel the world", "Spend time with family", "Chase one big dream", "Party hard and enjoy it"] },
    { q: "What's the biggest risk you've ever taken?",               opts: ["Career change", "Moving cities/countries", "A relationship leap", "Something financial"] },
    { q: "What do you think happens after we die?",                  opts: ["Heaven/Hell", "Reincarnation", "Nothing — lights out", "I genuinely don't know"] },
    { q: "What's your biggest regret so far?",                       opts: ["A missed opportunity", "A broken relationship", "Not starting sooner on a goal", "Something I'd never say out loud"] },
    { q: "If you could live in any decade, which would you pick?",   opts: ["The 70s", "The 80s", "The 90s", "I like right now"] },
    { q: "What would you want your legacy to be?",                   opts: ["A loving parent/partner", "A successful career", "An adventure-filled life", "Making people laugh"] },
    { q: "One thing you'd change about how you were raised?",        opts: ["More freedom", "More discipline", "More emotional support", "I wouldn't change anything"] },
    { q: "How do you feel about death?",                             opts: ["I think about it a lot", "I try not to think about it", "I've made peace with it", "It genuinely scares me"] },
    { q: "At what age do you think you were happiest?",              opts: ["Childhood — no responsibilities", "Teens — felt invincible", "20s — freedom and energy", "Right now, actually"] },
    { q: "What is success to you?",                                  opts: ["Financial freedom", "Doing work I love", "Strong relationships", "Feeling healthy and at peace"] },
    { q: "How do you feel about where you are in life right now?",   opts: ["Exactly where I want to be", "A bit behind where I hoped", "Off-track but getting there", "Completely lost — and that's okay"] },
    { q: "If you could give your younger self one piece of advice?", opts: ["Worry less about what people think", "Take more risks earlier", "Save your money", "Don't date that person"] },
    { q: "What's the most important lesson life has taught you so far?", opts: ["People will surprise you — good and bad", "Nothing lasts forever, so enjoy it", "You can't please everyone", "The only constant is change"] },
    { q: "What part of your life do you most want to change in the next year?", opts: ["My career or finances", "My relationships", "My health or lifestyle", "My relationship with myself"] },
    { q: "What's something you keep waiting to be 'ready' for?",     opts: ["Starting a creative project", "Having a difficult conversation", "A major life commitment", "Taking care of my health properly"] },
    { q: "Is there a version of your life you chose NOT to live that you still wonder about?", opts: ["A different career path", "A relationship that didn't happen", "Moving somewhere new", "A simpler, quieter life"] },
  ],
  wild: [
    { q: "What's the most illegal thing you've ever done?",          opts: ["Jaywalked / minor traffic", "Something involving substances", "Something I can't say here", "I'm basically a saint"] },
    { q: "Your most embarrassing drunk story involves...",           opts: ["Saying something I regret", "A physical incident", "A total stranger", "I was sober! I swear."] },
    { q: "Have you ever stalked an ex's social media recently?",     opts: ["Yes, this week", "Yes, occasionally", "Only once after the breakup", "Never — I'm evolved"] },
    { q: "If your texts were projected here right now, how nervous are you?", opts: ["0/10 — nothing to hide", "3/10 — mildly concerned", "7/10 — pretty nervous", "10/10 — please don't"] },
    { q: "What's a secret you've never told anyone in this room?",   opts: ["Something about work", "Something romantic", "Something embarrassing", "Not telling — DRINK."] },
    { q: "Would you rather lose all your money or all your memories?", opts: ["Lose money", "Lose memories", "Neither — this is cruel", "Depends on the memories"] },
    { q: "What's the most scandalous text you've ever sent?",        opts: ["A spicy late-night text", "A passive-aggressive message", "A wrong-person accident", "I delete everything"] },
    { q: "On a scale of 1-4, how good are you in bed?",              opts: ["1 — still learning", "2 — getting there", "3 — pretty solid", "4 — legendary"] },
    { q: "Have you ever pretended to be someone you're not online?", opts: ["Yes, with a fake profile", "Yes, just exaggerated a bit", "No, but I've been tempted", "Absolutely not"] },
    { q: "Worst lie you've told to get out of plans?",               opts: ["Fake illness", "Family emergency", "Work emergency", "I just ghost — no excuse given"] },
    { q: "What's the most embarrassing thing on your phone right now?", opts: ["A cringey photo album", "A group chat I should leave", "Browsing history I can't explain", "My notes app — do NOT open"] },
    { q: "Have you ever done something purely to make someone jealous?", opts: ["Yes and it worked", "Yes but it backfired", "I wanted to but didn't", "Never — I'm above that"] },
    { q: "Have you ever been in a physical fight?",                  opts: ["Yes, more than once", "Yes, once", "Almost, but it didn't happen", "Never — I talk my way out"] },
    { q: "What's the most chaotic night out you've ever had?",       opts: ["Lost someone in the group", "Ended up in a completely different city", "A regrettable decision was made", "I genuinely don't remember"] },
    { q: "Have you ever completely reinvented yourself after a breakup?", opts: ["Yes — full glow-up mode", "Somewhat — changed a few things", "Tried to and failed", "No — I stayed exactly the same"] },
    { q: "Weirdest thing you've done when nobody was watching?",     opts: ["Full concert performance alone", "Talked to myself out loud for ages", "Cried at something embarrassingly minor", "Something I will take to my grave"] },
  ],
  nostalgia: [
    { q: "What childhood fear do you lowkey still have?",            opts: ["The dark", "Something under the bed", "Heights", "Being home alone"] },
    { q: "What best describes your teenage self?",                   opts: ["The class clown", "The quiet one", "Tried too hard to be cool", "Genuinely didn't care"] },
    { q: "What show or movie defined your childhood?",               opts: ["A cartoon series", "A Disney/Pixar film", "A teen drama", "Something my parents shouldn't have let me watch"] },
    { q: "What's your most cringe teenage memory?",                  opts: ["Something I said to a crush", "A fashion choice I made", "A social media post", "A phase I went through"] },
    { q: "What did you want to be when you grew up?",                opts: ["Something creative (artist, actor)", "Something heroic (doctor, firefighter)", "Something cool (athlete, pop star)", "I genuinely had no idea"] },
    { q: "Your first heartbreak was caused by...",                   opts: ["A romantic rejection", "Losing a friendship", "Moving away or someone leaving", "Something family-related"] },
    { q: "What were you like at school?",                            opts: ["Popular and sociable", "Nerdy and studious", "Sporty and competitive", "On the fringes — doing my own thing"] },
    { q: "What's something from your childhood you genuinely miss?", opts: ["Having zero responsibilities", "A specific toy or game", "Saturday morning cartoons", "Not having a phone"] },
    { q: "How would your childhood best friend describe you back then?", opts: ["Loud and always laughing", "Bossy but loyal", "The shy one who warmed up", "The one with the wildest ideas"] },
    { q: "What's the most trouble you ever got into as a kid?",      opts: ["Sneaking out", "Breaking something expensive", "Lying to parents about where I was", "A fight or falling out with someone"] },
    { q: "What's a song that instantly takes you back to a specific memory?", opts: ["A childhood bedroom song", "A teen heartbreak anthem", "A car ride with family", "A night out I'll never forget"] },
    { q: "What was your first job and how bad was it?",              opts: ["Retail — soul-crushing", "Food service — never again", "It was actually fine", "I didn't have a proper job young"] },
    { q: "What trend from your past do you secretly wish would come back?", opts: ["A fashion era", "An old social media platform", "A music genre or artist", "A simpler pre-internet habit"] },
    { q: "What did teenage you think you'd have figured out by now?", opts: ["A stable career and savings", "Being in a serious relationship", "Knowing exactly who I am", "Just... more than this"] },
  ],
  opinions: [
    { q: "What's your most controversial food opinion?",             opts: ["Pineapple belongs on pizza", "Cilantro tastes like soap and ruins food", "Ketchup doesn't belong on eggs", "Breakfast food is overrated"] },
    { q: "Which overrated thing do you genuinely not get the hype about?", opts: ["A hugely popular TV show", "A beloved food or drink", "A famous travel destination", "A cultural phenomenon everyone loves"] },
    { q: "What's your hottest take on social media?",                opts: ["Instagram ruins relationships", "Twitter/X is pure toxicity", "TikTok is genuinely rotting brains", "LinkedIn is the most fake platform"] },
    { q: "What's an unpopular opinion you'd die on a hill for?",     opts: ["Something about pop culture", "Something about dating/relationships", "Something about society/politics", "Something about food or lifestyle"] },
    { q: "Which life milestone is the most overrated?",              opts: ["Buying a house", "Getting married", "Having kids", "Going to university"] },
    { q: "Most overrated quality people claim to want in a partner?", opts: ["Tall", "Funny", "Ambitious", "Kind"] },
    { q: "What do you secretly judge people for?",                   opts: ["Bad taste in music or TV", "Being rude to service staff", "Excessive social media posting", "Being chronically late"] },
    { q: "What's wrong with how most people spend their money?",     opts: ["Too much on going out", "Overpriced coffee addiction", "Buying things to impress others", "Subscriptions they never use"] },
    { q: "What do you think is the most toxic thing normalised in dating culture?", opts: ["Playing hard to get", "Keeping situationships going", "Ghosting", "Treating dates like job interviews"] },
    { q: "Which popular personality type label is the most overused?", opts: ["'I'm an introvert'", "'I'm an empath'", "'I'm a Virgo, that's why'", "'I have attachment issues'"] },
    { q: "What's a widely believed life advice you think is actually terrible?", opts: ["'Follow your passion'", "'Everything happens for a reason'", "'Never go to bed angry'", "'You have to love yourself first'"] },
    { q: "Which generation gets the most unfair criticism?",         opts: ["Boomers", "Gen X", "Millennials", "Gen Z"] },
    { q: "Which hobby do you find unbearably overrated?",            opts: ["Golf", "Yoga and wellness culture", "Craft beer obsession", "Running — and talking about running"] },
    { q: "What's your honest opinion on therapy culture?",           opts: ["Essential — everyone should go", "Helpful but over-relied on", "Great in theory, hit-or-miss in practice", "Too much is online content, not real work"] },
  ],
  hypotheticals: [
    { q: "Would you rather know the exact date of your death or the exact cause?", opts: ["The date — I'd plan everything", "The cause — I'd avoid it", "Neither — ignorance is bliss", "Both, I want the full picture"] },
    { q: "If you had to switch careers tomorrow, what would you do?", opts: ["Something creative", "Something outdoors or physical", "Something that helps people", "I'd start a business"] },
    { q: "Would you rather be famous but broke, or rich but completely unknown?", opts: ["Famous and broke — the attention is worth it", "Rich and unknown — peace and freedom", "Depends on the kind of fame", "I couldn't handle either extreme"] },
    { q: "If you could only eat one meal for the rest of your life, what would it be?", opts: ["A classic roast", "A big breakfast", "Pizza or pasta", "Something from another culture"] },
    { q: "Would you rather have a rewind button or a pause button for your life?", opts: ["Rewind — I'd fix so much", "Pause — I need more time", "Rewind for one specific moment", "Pause during the best moments"] },
    { q: "If your life were a movie genre, what would it be?",        opts: ["Romantic comedy", "Thriller with twists", "Coming-of-age drama", "Low-budget indie nobody watched"] },
    { q: "Would you rather give up alcohol or social media for a year?", opts: ["Give up alcohol — easy", "Give up social media — easy", "Alcohol... but it'd be hard", "Social media... but it'd be hard"] },
    { q: "If you could live anywhere in the world, where would you go?", opts: ["Somewhere warm and coastal", "A buzzing international city", "Peaceful countryside", "Wherever I am now, honestly"] },
    { q: "Would you rather always know when someone is lying, or be able to lie without anyone ever knowing?", opts: ["Know when others lie — trust is everything", "Lie freely — the power is appealing", "Know when others lie — I'd use it carefully", "Lie freely — just white lies, I promise"] },
    { q: "If you could be world-class at one thing overnight, what would you pick?", opts: ["A sport or physical skill", "A creative skill (music, art, writing)", "A social skill (public speaking, charisma)", "Something that makes money"] },
    { q: "You can have one superpower but it only works on Tuesdays. Do you want it?", opts: ["Yes — Tuesday time travel it is", "Only if I can choose which power", "No — too unreliable", "Depends entirely on the power"] },
    { q: "If you had to lose one of your senses, which would you sacrifice?", opts: ["Smell", "Taste", "Touch", "None — this question is cruel"] },
    { q: "Would you take a pill that made you feel confident forever, knowing it might not reflect reality?", opts: ["Yes, immediately", "Yes, but with some guilt", "No — I'd rather feel real", "Depends what reality I'd be distorted from"] },
    { q: "If you could relive one day of your life, which would you pick?", opts: ["A childhood memory", "A milestone achievement", "A day with someone I've lost", "A perfect ordinary day I didn't appreciate enough"] },
  ],

  money: [
    { q: "How would you honestly describe your relationship with money?",  opts: ["I'm good with it — always have been", "I try but still overspend", "Money stresses me out constantly", "Money comes and goes and I'm okay with that"] },
    { q: "How much of your salary is going on rent or housing?",           opts: ["Under 25%", "25-40%", "Over 40% — it's painful", "I don't pay rent (lucky me)"] },
    { q: "What's the most ridiculous thing you've splurged on?",           opts: ["Fashion or accessories", "Tech or gadgets", "A wild night out", "Something I'll never admit"] },
    { q: "How much debt are you carrying right now?",                       opts: ["None", "A little — manageable", "A lot — it keeps me up at night", "Student loans don't count, right?"] },
    { q: "Do you have a savings account you actually put money in?",        opts: ["Yes and it's growing", "Yes but I keep raiding it", "Sort of — it's more of a vibe", "No — I live paycheque to paycheque"] },
    { q: "What's your relationship with splitting the bill on a date?",     opts: ["Always split equally", "Whoever asked pays", "I pay the first time", "It depends on the vibe"] },
    { q: "How would you spend a surprise $10,000?",                        opts: ["Invest or save it", "Travel immediately", "Clear debt", "Spend it all on something fun"] },
    { q: "Do you actually know your monthly outgoings?",                    opts: ["Yes, I track everything", "Roughly, yes", "Not really", "Absolutely not"] },
    { q: "Have you ever lied about how much something cost?",               opts: ["Yes, upwards (bragging)", "Yes, downwards (hiding it)", "Both, depending on who's asking", "Never — I'm an open book"] },
    { q: "Would you marry someone significantly wealthier for the lifestyle?", opts: ["Yes, if I liked them too", "No — that feels wrong to me", "I already have / would if they asked", "I'd deny it but probably yes"] },
    { q: "What's your most irresponsible money habit?",                    opts: ["Impulse online shopping at midnight", "Taxis when I should walk", "Eating out when the fridge is full", "Never checking my bank balance"] },
    { q: "Do you think your financial situation is your own fault?",        opts: ["Yes, mostly", "Partly — life circumstances played a role", "No — the system is rigged", "I try not to assign blame"] },
  ],

  travel: [
    { q: "What kind of traveller are you?",                                 opts: ["Over-planner — itinerary for every hour", "Rough idea, figure it out as I go", "Pure spontaneous chaos", "I prefer staying home honestly"] },
    { q: "What's the best trip you've ever taken?",                        opts: ["A solo adventure", "A couple's trip", "A group holiday", "A family trip I didn't expect to love"] },
    { q: "What's been your biggest travel disaster?",                       opts: ["Missed a flight or connection", "Lost luggage or documents", "Ended up somewhere totally unexpected", "A travel companion who ruined it"] },
    { q: "How do you feel about travelling solo?",                          opts: ["Love it — done it multiple times", "I'd like to try it", "Too nervous, not for me", "Already planning my next one"] },
    { q: "Which would you rather do?",                                      opts: ["Backpack on a budget for 3 months", "5-star luxury trip for 1 week", "Road trip with no fixed destination", "Settle in one foreign city for a month"] },
    { q: "What's the most surprising place you've ever been to?",          opts: ["A small town in the middle of nowhere", "A big city that blew me away", "A country whose reputation I needed to see for myself", "I haven't been anywhere that surprising yet"] },
    { q: "How do you pick where to travel next?",                           opts: ["Food and cuisine", "Weather and beaches", "History and culture", "Wherever flights are cheapest"] },
    { q: "Have you ever extended a trip because you didn't want to leave?", opts: ["Yes, multiple times", "Yes, once", "Wanted to but couldn't", "Never — I like going home"] },
    { q: "What type of accommodation do you prefer?",                       opts: ["Luxury hotel", "Cozy boutique or B&B", "Airbnb apartment", "Hostel or budget option"] },
    { q: "What's your most controversial travel take?",                     opts: ["Tourist traps are usually worth it", "You learn more from resorts than backpacking", "Some countries are genuinely overrated", "Travelling doesn't make you a better person"] },
    { q: "What destination is on your list that people think is odd?",      opts: ["Somewhere politically complicated", "A country no one I know has been to", "A place with extreme weather", "Somewhere totally off the tourist trail"] },
    { q: "What do you always overpack?",                                    opts: ["Clothes I never wear", "Toiletries and medicine", "Books or entertainment", "Snacks I could've bought there"] },
  ],

  work: [
    { q: "How do you really feel about your current job?",                  opts: ["I genuinely love it", "It pays the bills — fine", "I'm actively looking for a way out", "It's complicated"] },
    { q: "Have you ever cried at work or because of work?",                 opts: ["Yes, at my desk", "Yes, in the bathroom or car", "Nearly, but held it together", "No — I never let it get there"] },
    { q: "How honest are you about your real opinion in meetings?",         opts: ["Brutally honest — always", "I filter but share my view", "I mostly stay quiet", "I say what's needed and move on"] },
    { q: "What's your biggest complaint about your workplace?",             opts: ["The management", "The politics and gossip", "The pay or lack of recognition", "The culture and people"] },
    { q: "How much of your colleagues' salaries do you know?",              opts: ["I know roughly", "I know exactly", "I've guessed but don't know", "I have no idea and prefer it that way"] },
    { q: "Have you ever taken credit for someone else's work, or had yours taken?", opts: ["I've had mine taken", "I may have taken someone else's", "Both, if I'm honest", "Neither — clean record"] },
    { q: "How do you feel about working from home?",                        opts: ["Love it — never going back", "Prefer the office actually", "Hybrid is the only right answer", "The isolation has gotten to me"] },
    { q: "Would you take a 20% pay cut to love your job?",                  opts: ["Yes immediately", "Probably, if it was the right role", "No — money matters too much", "I already did this"] },
    { q: "How often do you actually work during your working hours?",       opts: ["Every minute, genuinely", "Most of it", "Maybe 60%", "I'm basically paid to exist"] },
    { q: "Have you ever seriously considered quitting without another job lined up?", opts: ["Yes and I did it", "Yes and I talked myself out of it", "Thought about it but never seriously", "No — too risky for me"] },
    { q: "What's the most unprofessional thing you've done at work?",       opts: ["Complained about a manager to colleagues", "Browsed dating apps during a meeting", "Made up a reason to work from home", "Something I'll never put in writing"] },
    { q: "What does your ideal working life look like?",                    opts: ["Remote, flexible, no fixed hours", "Busy office surrounded by people", "Own business, total control", "Part-time with time for everything else"] },
  ],

  deepdark: [
    { q: "What's a thought you've had that genuinely scared you?",          opts: ["Something about a relationship ending", "Something about mortality", "Something about who I really am", "A thought I'm not ready to name"] },
    { q: "What's the part of yourself you work hardest to hide from people?", opts: ["My insecurity", "My anger", "My loneliness", "How little I have it together"] },
    { q: "What do you most fear people finding out about you?",             opts: ["That I'm not as confident as I seem", "That I've done something I'm ashamed of", "That I feel lost", "Something specific I won't say"] },
    { q: "When did you last feel truly lonely?",                            opts: ["Recently — I'm in it now", "Not long ago", "It's been a while", "I keep too busy to feel it"] },
    { q: "What relationship in your life do you think is slowly fading?",   opts: ["A friendship I've been neglecting", "A family bond that feels strained", "A romantic connection losing its spark", "All of the above, slowly"] },
    { q: "What do you wish someone in your life would just say to you?",    opts: ["That they're proud of me", "That I'm enough as I am", "That they see how hard I'm trying", "Something I can't say out loud here"] },
    { q: "What's something you've never forgiven yourself for?",            opts: ["Hurting someone who didn't deserve it", "Not being there when I should have been", "Wasting a period of my life", "Something I'm not ready to say"] },
    { q: "What emotion do you find hardest to feel in front of others?",    opts: ["Sadness or grief", "Fear or vulnerability", "Anger", "Joy — I feel guilty when I'm too happy"] },
    { q: "Do you feel truly known by anyone in your life?",                 opts: ["Yes — completely", "By one or two people, partially", "I show different pieces to different people", "No, and that doesn't go away"] },
    { q: "What version of yourself are you most afraid of becoming?",       opts: ["Bitter and resentful", "Successful but empty", "Alone and disconnected", "Exactly like someone in my family"] },
    { q: "Is there something you should have said to someone, but never did?", opts: ["An apology I owe", "Feelings I never expressed", "Gratitude I held back", "A goodbye I didn't get to say"] },
    { q: "What part of your childhood still shows up in your adult life?",  opts: ["The need for approval", "Difficulty trusting people", "An old fear I never outgrew", "A strength forged from something hard"] },
  ],
};
